exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = sh -c 'waybar &'
exec-once = awww-daemon
exec-once = awww img "$HOME/Pictures/wallpapers/walls/gray-mountain-cloudy.jpg" --transition-type none
