hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
  hl.exec_cmd("sh -c 'waybar &'")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("awww img \"$HOME/Pictures/wallpapers/walls/gray-mountain-cloudy.jpg\" --transition-type none")
end)
